server:
  port: 9001

spring:
  application:
    name: zuul-gateway

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  #    instance-id:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  retryable: true
  routes:
    order-service:
      path: /order/**