server:
  port: 9090

spring:
  application:
    name: order-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false

logging.level.com.zhss.order.service.InventoryService: DEBUG

########## ribbon 配置重试  ##############3
inventory-service:
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 6000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    retryableStatusCodes: 500,408
    OkToRetryOnAllOperations: true
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

########## ribbon 不与eureka同时使用； ##########
#inventory-service:
#  ribbon:
#    listOfServers: 127.0.0.1:8082
#
#credit-service:
#  ribbon:
#    listOfServers: 127.0.0.1:8081,127.0.0.1:8084
#
#wms-service:
#  ribbon:
#    listOfServers: 127.0.0.1:8083

feign:
  client:
    config:
      inventory-service:
        loggerLevel: full