server:
  port: 9090

spring:
  application:
    name: order-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false


logging.level.com.zhss.order.service.InventoryService: DEBUG

feign:
  client:
    config:
      inventory-service:
        loggerLevel: full